<?php if ($this->pageCount): ?>
<!-- First page link -->
<?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
        Đầu
    </a> |
    <?php else: ?>
    <span class="disabled">Đầu</span> |
    <?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
    <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
        &lt; Lùi
    </a> |
    <?php else: ?>
    <span class="disabled">&lt; Lùi</span> |
    <?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
        <a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a> |
        <?php else: ?>
            <?= $page; ?> |
        <?php endif; ?>
    <?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
        Tới &gt;
    </a> |
    <?php else: ?>
    <span class="disabled">Tới &gt;</span> |
    <?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
    <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
        Cuối
    </a>
    <?php else: ?>
    <span class="disabled">Cuối</span>
    <?php endif; ?>

</div>
<?php endif; ?>