<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Newsletter</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <?php if ('production' == APPLICATION_ENV): ?>
    <link href="/resources/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/resources/js/underscore/underscore.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="/resources/twitter-bootstrap/js/bootstrap.min.js"></script>
    <?php else: ?>
    <link href="/resources/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/resources/js/underscore/underscore.js"></script>
    <script type="text/javascript" src="/resources/js/jquery/jquery.js"></script>
    <script type="text/javascript" src="/resources/twitter-bootstrap/js/bootstrap.js"></script>
    <?php endif ?>

    <link href="/resources/css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="/resources/js/crawler.js"></script>
    <script type="text/javascript" src="/resources/js/simple-paging.js"></script>
    <?php echo $this->headScript() ?>

</head>
<body>
<div id="container">
    <div id="header">
        <div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="brand" href="./index.html">QuangCaoNewsletter.com</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li>
                                <a href="/newsletters">Newsletter</a>
                            </li>
                            <li>
                                <a href="/news">Tin Tức</a>
                            </li>
                            <li>
                                <a href="/ads">Quảng Cáo</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="center">
    <?php echo $this->layout()->content; ?>
    </div>
    <div id="footer">Copyright &copy; 2012 by <a href="http://quangcaonewsletter.com">quangcaonewsletter.com</a></div>
</div>
</body>
</html>